### ISSUE TITLE
adding a tab getting class cke_dialog_tab_disabled

### ISSUE THREAD

**Issue by bastoune** [ckeditor/ckeditor-releases#31]
Using Ckeditor 4.4.7, trying in recents browsers.

I am trying to add to the dialog plugin my own tab.

Here  is how I did :

    var FuncDialogNrImage;
    var pluginName = 'imageBrowser';
    var dialog;
    CKEDITOR.plugins.add('imageBrowser',
        {
            requires: ['iframedialog'],
    
            init: function(editor)
            {
                dialog = this;
    
                FuncDialogNrImage = editor._.FuncDialogNrImage = CKEDITOR.tools.addFunction( dialogFunctionImage,  editor );
                CKEDITOR.on( 'dialogDefinition', function( ev )
                {
                    // Take the dialog name and its definition from the event
                    // data.
                    var dialogName = ev.data.name;
    
                    var dialogDefinition = ev.data.definition;
                    if (dialogName == "link" || dialogName == "image" )
                    {
                        dialogDefinition.minWidth = 800;
                        dialogDefinition.minHeight = 500;
                    }
    
                    // Check if the definition is from the dialog we're
                    // interested on (the 'Link' dialog).
                    if ( dialogName == 'image' || dialogName == 'flash')
                    {
                        if(document.location.pathname.indexOf('administrator') > -1)
                        {
                            path = '../';
                        }else
                        {
                            path = '';
                        }
                        dialog = dialogDefinition;
                        // Add a new tab to the 'Link' dialog.
                        dialogDefinition.removeContents('imageBrowserTab');
                        dialogDefinition.addContents({
                            id : 'imageBrowserTab',
                            label : 'Médiathèque',
                            title : 'Médiathèque',
                            elements : [
                                {
                                    id : 'imageBrowser',
                                    label : 'Médiathèque',
                                    type : 'html',
                                    html: '<iframe src="/backend.php/Mediatheque/Browser/'+dialogName+'" id="iframeNextgen" allowtransparency="1" style="width:800px;height:490px;margin:0;padding:0;vertical-align: auto;"></iframe>'
                                }
                            ]
                        });
                    }
                });
            }
        });
    
    function dialogFunctionImage(string)
    {
    
        var dialogName = dialog.dialog.getName();
        if(string.indexOf("internal://") !== -1)
        {
            dialogName = 'link';
        }
    
    
        if (dialogName == 'image')
        {
            dialog.dialog.selectPage('info');
            dialog.dialog.setValueOf('info', 'txtUrl', string);
        }
    
        if (dialogName == 'link')
        {
            dialog.dialog.selectPage('info');
            dialog.dialog.setValueOf('info', 'url', string);
        }
        if (dialogName == 'flash')
        {
            dialog.dialog.selectPage('info');
            dialog.dialog.setValueOf('info', 'src', string);
        }    
    }

It mostly works but the problem I have ius that the tab is unclickable with an added 'cke_dialog_tab_disabled' class.
The wierdest thing is that the content is well generated in the dom. 

Bellow is the html generated :

**In the dialog**

    <a class="cke_dialog_tab cke_dialog_tab_disabled" cke_last="" title="Médiathèque" id="cke_imageBrowserTab_173" href="javascript:void(0)" tabindex="-1" hidefocus="true" role="tab" style="-webkit-user-select: none;">Médiathèque</a>

**In the content**

    <div role="tabpanel" id="cke_172_uiElement" class="cke_dialog_ui_vbox cke_dialog_page_contents" style="width: 100%; display: none;" aria-labelledby="cke_imageBrowserTab_173" name="imageBrowserTab" aria-hidden="true">
<table role="presentation" cellspacing="0" border="0" style="width:100%;float:none;" align="left">
<tbody>
<tr>
<td role="presentation" class="cke_dialog_ui_vbox_child">
  <iframe src="/backend.php/Mediatheque/Browser/image" id="iframeNextgen" allowtransparency="1" style="width:800px;height:490px;margin:0;padding:0;vertical-align: auto;" class="cke_dialog_ui_html"></iframe></td></tr></tbody></table></div>

**Comment by Reinmar** [comment]
If you think that you encountered a bug, then please report it on http://dev.ckeditor.com. But in such case please simplify the scenario and explain what is the expected and actual result, because it's not clear.

If you have a question about the dialog API, then please ask it on http://stackoverflow.com or other forum/Q&A site.

This repository contains only releases and here we keep bugs related to releases, not the project itself.

**Comment by jayendra-sharan** [comment]
I had similar issue. Drop the id attribute from the html mark up inside elements. It worked in my case.

`` id="iframeNextgen"``

``html: '<iframe src="/backend.php/Mediatheque/Browser/'+dialogName+'" id="iframeNextgen" allowtransparency="1" style="width:800px;height:490px;margin:0;padding:0;vertical-align: auto;"></iframe>'``
