### ISSUE TITLE
Lost half of the successive spaces

### ISSUE THREAD

**Issue by zymiboxpay** [ckeditor/ckeditor-releases#32]
Using Ckeditor 4.4.5

When I input four spaces continuously in the ckeditor and then use the getData() method, what I expect is

"& nbsp;& nbsp;& nbsp;& nbsp;",

but what I got is this

" & nbsp; & nbsp;"

**Comment by Reinmar** [comment]
There are normal spaces between the non-breakable ones, so in total there are 4 spaces. This is correct.

PS. This isn't a place to report bugs in CKEditor. Please do this on http://dev.ckeditor.com next time.

**Comment by zymiboxpay** [comment]
Thanks!
