### ISSUE TITLE
Subdomain fails loading plugins

### ISSUE THREAD

**Issue by ophian** [ckeditor/ckeditor-releases#34]
eg. I have two blog sites domain.com/ and name.domain.com.

In both sites I have the same Blog software containing the ckeditor lib in web-root/lib.

Site 1 works and loads well, including my personal plugins, which are in `libs/ckeditor/plugins/myplugin` and are configured through a custom config. The Plugin failing in special does not hook into toolbar, so it is just added to the extraPlugins config.

I get an error for the subdomain site:
`uncaught exception: [CKEDITOR.resourceManager.load] Resource name "myplugin" was not found at
http://name.domain.com/lib/ckeditor/plugins/myplugin/plugin.js` 

I can access `domain.com/lib/ckeditor/plugins/myplugin/plugin.js` in browser, but not `name.domain.com/lib/ckeditor/plugins/myplugin/plugin.js`. Directory structure is `/var/wwww/site1/html` for the first and and `/var/wwww/site1/html/name` for the second. Second is a htaccess restricted site.

I checked this on both 4.4.6 and 4.4.7 full releases.

Do you have any ideas on this, being a bug in CKE?

**Comment by wwalc** [comment]
I did not fully understand your case, but are you enabling any additional plugins loaded from different domain with `CKEDITOR.plugins.addExternal`?

See http://cdn.ckeditor.com/#plugins for an inspiration.

PS. The right place to report issues with CKEditor is http://dev.ckeditor.com/

**Comment by ophian** [comment]
No, not `addExternal` and the domain is the same. The second ist just a subdomain and is the one which fails.

We do it like this, eg 
```
CKEDITOR.replace('thetextarea', {
extraPlugins : manuallyAddedPluginNamesVar,
toolbar : 'predefinedToolbarVar',
language : 'blogLanguageVar',
customConfig : 'customConfigPathVar',
...
```

I see, next time I'll check into the right issue tree, thanks.

**Comment by ophian** [comment]
Dixed it. Was a strange issue on my side, nothing to worry for cke. Thanks.
