### ISSUE TITLE
Cannot input Chinese/Others after setting text BOLD or UNDERLINE

### ISSUE THREAD

**Issue by kyleada** [ckeditor/ckeditor-releases#40]
Hi
I tested this page and  found a bug.

http://ckeditor.com/demo#full

When I input some English text and set them BOLD or UNDERLINE, then I change the input method to want to input some Chines and click the ENTER BUTTON to make a newline. However, I cannot input Chinese ever

I tried some different input methods, all of them do like this.

**Comment by Reinmar** [comment]
This is a known bug and we're working on a solution for it. There's no single ticket that groups all kinds of related issues, but you can follow http://dev.ckeditor.com/ticket/13377.

PS. Please not that this issue tracker exists for release specific issues. For general project issues use http://dev.ckeditor.com
