### ISSUE TITLE
Copy paste from google docs

### ISSUE THREAD

**Issue by user936** [ckeditor/ckeditor-releases#47]
Hello,
There seems to be a problem with pasting content from google docs using google chrome. ckeditor transforms all the pasted content to bold, surrounding them with <strong> tags when in fact they are not bold.

Here is a sample google doc to test with https://docs.google.com/document/d/1WgI8GMo47XU-RWgkDf4_m7P5hiTkiTCc4t06V9WIK2E/edit 

The problem can be verified with google chrome using the ckeditor sample page:
http://ckeditor.com/demo
I am not sure about other browsers.

**Comment by AnnaTomanek** [comment]
Please not that this issue tracker exists for release-specific issues. If you want to report a bug in CKEditor, please use the official tracker at http://dev.ckeditor.com.

**Comment by wwalc** [comment]
See also this: https://dev.ckeditor.com/ticket/13877 - might be a duplicate of that ticket.

**Comment by user936** [comment]
It is a duplicate, thank you.
