### ISSUE TITLE
CKEDITOR.htmlParser.fragment.fromBBCode need ignore parse of inside of code tag.

### ISSUE THREAD

**Issue by martec** [ckeditor/ckeditor-releases#48]
Hi,

i need that CKEDITOR.htmlParser.fragment.fromBBCode function not parse content of inside of code tag ( [code][/code] ). 
like sceditor https://github.com/samclarke/SCEditor/blob/master/src/lib/SCEditor.js#L1613

**Comment by mlewand** [comment]
Release repository is not meant to be used for editor bugs. Please use [our issue tracker](dev.ckeditor.com) for that.

You can always find more information in [Reporting Issues guide](http://docs.ckeditor.com/#!/guide/dev_issues_readme).
