### ISSUE TITLE
cache-busting build number missing from editor.css urls

### ISSUE THREAD

**Issue by jkallay1** [ckeditor/ckeditor-releases#52]
Rules for putting the right background image on toolbar buttons appear both inline on each button's span element and are also defined in the skin's editor.css. The url in the former is an absolute path with the build number in the query string, but the latter is a relative url with no build number, and the latter is the one with higher precedence of a !important attribute. This allows an older version of the icons image to be used in the browser, such that the buttons show the wrong images.

**Comment by jswiderski** [comment]
I believe that this is what you are talking about - http://dev.ckeditor.com/ticket/10685

**Comment by jkallay1** [comment]
That's the one.
