### ISSUE TITLE
How to get full version of ck.editor (not compressed version)

### ISSUE THREAD

**Issue by caok2709** [ckeditor/ckeditor-releases#54]
Anyone can send me a link to the full version of ck.editor?
I don't wan to use .min version

**Comment by mlewand** [comment]
Well there are multiple ways to obtain unminified version of CKEditor. The preferred way is to checkout CKEditor 4 source code directly from the [offical CKEditor repository](https://github.com/ckeditor/ckeditor-dev).

If you're not familiar with Git source code versioning system, you could also get full sources using our [CKEditor builder](http://ckeditor.com/builder) - just make sure to select "Source (Big N’Slow)" below the download button.

**Comment by caok2709** [comment]
Thx!

**Comment by mlewand** [comment]
You're welcome. :)
