### ISSUE TITLE
Paste From Word files missing

### ISSUE THREAD

**Issue by Tim-Intellipharm** [ckeditor/ckeditor-releases#56]
The dev and release repositories have different files for the pastefromword plugin
https://github.com/ckeditor/ckeditor-dev/tree/master/plugins/pastefromword
https://github.com/ckeditor/ckeditor-releases/tree/master/plugins/pastefromword

**Comment by mlewand** [comment]
Don't worry, that's actually fine! :) The reason for this is that CKBuilder (app that creates optimized CKEditor from our sources) inlines as much files as it can, e.g. js code, images. So that  you end up with smaller CKEditor.

**Comment by Tim-Intellipharm** [comment]
I am using jspm to pull down the repository, and I cannot get the Paste From Word plugin to work. I cannot load the plugin

**Comment by mlewand** [comment]
PFW plugin is working perfectly fine in our ckeditor-releases repository. To check that you could simply  use GitHub's "Download ZIP" button in ckeditor-releases master branch. So it looks to be jspm issue.
