### ISSUE TITLE
editor.on('change') is not fired after pasting from clipboard for the first two input symbols

### ISSUE THREAD

**Issue by sazonov** [ckeditor/ckeditor-releases#58]
Hi, guys! I registered on your official issue tracker but email verification letter is not coming, I tried to send it three times and waited for 30 minutes and it didn't work. So I put the issue here.

After pasting from clipboard something goes wrong and next two input chars do not cause emitting of 'change' event. It can be reproduced on your official demo page. From the third symbol all works properly. Could you please check that? Thanks :)

**Comment by f1ames** [comment]
Hello,
thanks for your input. This repo is not the correct place to report issues but I understand you had some problems with our bug tracker. The proper person will contact you soon to solve it so you can freely report new issue there in the future:)

As for the above issue, it is already reported as [#14675](http://dev.ckeditor.com/ticket/14675). I will add also your comment there.
