### ISSUE TITLE
How to use with angular2,@type dosen't has it.

### ISSUE THREAD

**Issue by TaylorPzreal** [ckeditor/ckeditor-releases#62]
i love ckeditor, i want to use with angular2, could you help me.

**Comment by f1ames** [comment]
Hello @TaylorPzreal,
we are happy to hear that! However, this is not  the proper place to ask general questions as this is ckeditor-release repository so only issues related to release process should be reported here.

There is no official driver for angular2 at the moment. You may look for some community projects like https://github.com/chymz/ng2-ckeditor or look for some guaidance on SO - http://stackoverflow.com/questions/35978025/angular2-ckeditor-use.
