### ISSUE TITLE
way to get the html and text enclosed by range

### ISSUE THREAD

**Issue by minaseem** [ckeditor/ckeditor-releases#63]
There should be way to get the html and text enclosed by the range. This feature will be very useful.
extractContent() removes the enclosed content from the DOM.

**Comment by mlewand** [comment]
You're looking for http://docs.ckeditor.com/#!/api/CKEDITOR.dom.selection-method-getSelectedText.

Still, please do not report issues in CKEditor. The correct location of CKEditor issue tracker is: http://dev.ckeditor.com.
