### ISSUE TITLE
Image don't appear in preview area if URL was set from javascript

### ISSUE THREAD

**Issue by ryakoviv** [ckeditor/ckeditor-releases#64]
How I can paste URL from javascript and immediately see image in preview area?

**Comment by f1ames** [comment]
Hello @ryakoviv,
this is not a proper place to ask questions about CKEditor functionality. This is a repository strictly for CKEditor release packages.

You may refer to our [SDK](http://sdk.ckeditor.com/) and [docs](http://docs.ckeditor.com/#!/guide) while looking for the information. If you found an issue you may report it on [our official bugtracker](http://dev.ckeditor.com/). If you still will not be able to find an answer to your question you may look on [CKEditor on SO](http://stackoverflow.com/questions/tagged/ckeditor) (eventaully ask the question there).

**Comment by gitesh-purbia** [comment]
Got the same issue when i uploading image through uploadImage plugin. In the plugin in response for http request, plugin replace image via the javascript, so the changes does not reflecting in preview area. To resolve this issue i just added a line in link method of angular-ckeditor directive and working fine. I just do -:

ckeditor.$on('fileUploadResponse', ()=>{
   ngModel.$setViewValue(ckeditor.instance.getData() || '');
});

Add this line in link method of directive according to your condition, how you are inserting image.
