### ISSUE TITLE
Functions should not be defined inside loops

### ISSUE THREAD

**Issue by vasanthknatarajan** [ckeditor/ckeditor-releases#66]
I m using the CKEditor 4.6.2 version and when i build my project using team city, my build is failing because of the below issue in 21 places.

Functions should not be defined inside loops

**Comment by mlewand** [comment]
The proper place for reporting tickets is http:///dev.ckeditor.com

As a workaround for your particular case, if it's simply a linter errror I suggest you to add this rule to ignore list so you can build the app.
