### ISSUE TITLE
Issue with webpack

### ISSUE THREAD

**Issue by ruchern** [ckeditor/ckeditor-releases#67]
Installed the latest version of CKEditor and having an error with initiating it.

`TypeError: CKEDITOR.replace() is not a function`

I have included the following in my `app.js`

```javascript
window.CKEDITOR = require('ckeditor')
```

**Comment by mlewand** [comment]
Hi @ruchern, thanks for reporting the issue. This is a general CKEditor issue, so as such should be reported in https://github.com/ckeditor/ckeditor-dev repo.

Just a moment ago we got a report saying that CKE doesn't play well with TypeScript (ckeditor/ckeditor-dev#474) definition, however it looks to me that it's simply a webpack issue that the reporter is facing, in fact it looks pretty much the same thing that you've reported here. However I can't do a in-depth research on this ATM.

Can I ask you to take a look at ckeditor/ckeditor-dev#474 to see if it's the same issue there? Once we have a clarification we'll extract a general webpack feature request.

**Comment by ruchern** [comment]
Hi @mlewand,

Thank you for the reply. I will look into the issue as suggested by you and return with my feedback.

**Comment by ruchern** [comment]
Hi @mlewand, 

Apparently, #474 did not solve my problem. I am finding other ways to integrate this. It might be an issue integrating with Vue.js.

**Comment by mlewand** [comment]
@ruchern Let us know, as you have more feedback on that. If you find any troubles/need to discuss anything, feel free to ask here.

**Comment by ruchern** [comment]
@mlewand Sorry for the long follow-up as I am a bit busy with other stuff lately. Is this CKEditor compatible with ES6 (ES2015)?
