### ISSUE TITLE
HTTPS on the CKEditor website

### ISSUE THREAD

**Issue by FlorentTorregrosa** [ckeditor/ckeditor-releases#68]
Hello,

As a follow-up to https://github.com/ckeditor/ckeditor-releases/issues/38#issuecomment-307802512 and https://www.drupal.org/node/2885338 I open this issue.

I don't know if it is the right place for that but would it be possible for the CKEditor website to use HTTPS please?

It would ease the download of plugins using tools such as Composer. Currently in Drupal 8 there is the Webform module (https://www.drupal.org/project/webform) (and some other modules) which requires CKEditor plugins and provides a composer.json template to download those plugins using composer but the URL of those plugins are in HTTP.

So having the CKEditor website in HTTPS would avoid a lot of people to have to disable the "secure-http" option in Composer.

Thanks for any reply.

**Comment by milkovsky** [comment]
I agree with @FlorentTorregrosa, having the same issue.

**Comment by milkovsky** [comment]
Another solution would be - have a separate reository for every plugin on Github

**Comment by mlewand** [comment]
Thanks for the report. Currently our website folks are on holidays, so we need to wait a bit with the response.

> Another solution would be - have a separate reository for every plugin on Github

That would be a nice option, however we can't force third parties to move on GitHub.

**Comment by mlewand** [comment]
Good news, our website is now available through HTTPS protocol 🎉!

Plugins in the Add-ons Repository are also served using HTTPS.

**Comment by ygerasimov** [comment]
Looks https problem strikes back.

```
wget https://ckeditor.com/cke4/sites/default/files/colorbutton/releases/colorbutton_4.7.0.zip
--2018-09-26 08:47:29--  https://ckeditor.com/cke4/sites/default/files/colorbutton/releases/colorbutton_4.7.0.zip
Resolving ckeditor.com (ckeditor.com)... 13.33.231.13, 13.33.231.12, 13.33.231.85, ...
Connecting to ckeditor.com (ckeditor.com)|13.33.231.13|:443... connected.
ERROR: cannot verify ckeditor.com's certificate, issued by ‘CN=COMODO RSA Domain Validation Secure Server CA,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB’:
  Unable to locally verify the issuer's authority.
To connect to ckeditor.com insecurely, use `--no-check-certificate'.
```

**Comment by paulsally** [comment]
Yes, it seems it strucks again and again
https://ckeditor.com/cke4/sites/default/files/autogrow/releases/autogrow_4.11.4.zip" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed.

**Comment by f1ames** [comment]
@vokiel could you take a look on https://github.com/ckeditor/ckeditor4-releases/issues/68#issuecomment-605467085?
