### ISSUE TITLE
skin.js missing in monoo-lisa

### ISSUE THREAD

**Issue by WimWidgets** [ckeditor/ckeditor-releases#76]
There should be a `skin.js` file to config the skin, but there isn't:
https://github.com/ckeditor/ckeditor-releases/tree/master/skins/moono-lisa

**Comment by mlewand** [comment]
Moono-lisa is a default skin for the CKEditor 4 thus it gets inlined into the build for performance reasons. This is by design.

You could eventually start work with your dev version, and then build it.
