### ISSUE TITLE
Unable to access 'https://github.com/ckeditor/ckeditor-releases.git/

### ISSUE THREAD

**Issue by ffarman** [ckeditor/ckeditor-releases#77]
Using bower and works fine on my local machine.
However, Jenkins build fails with following error:
ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/ckeditor/ckeditor-releases.git", exit code of #128 fatal: unable to access 'https://github.com/ckeditor/ckeditor-releases.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

I suspect this could be due to this update:
https://githubengineering.com/crypto-removal-notice/

**Comment by sandyhuner** [comment]
So did you solve the problem?
