### ISSUE TITLE
Latest release version via the builder is broken

### ISSUE THREAD

**Issue by xoniq** [ckeditor/ckeditor-releases#87]
When getting a clean version from https://ckeditor.com/cke4/builder and adding a simple html to test CKEditor, the editor is not loading, both in the latest Chrome and Safari in macOS Mojave.

The test script i'm using (from documentation):

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>A Simple Page with CKEditor</title>
        <!-- Make sure the path to CKEditor is correct. -->
        <script src="ckeditor.js"></script>
    </head>
    <body>
        <form>
            <textarea name="editor1" id="editor1" rows="10" cols="80">
                This is my textarea to be replaced with CKEditor.
            </textarea>
            <script>
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace( 'editor1' );
            </script>
        </form>
    </body>
</html>
```

The editor loads, the toolbars show up, but its blocked, and when clicking a button it complains about not being active.

**EDIT:**

This seems to be only the issue when using the builder. Downloading it as a FULL package directly and testing the exact same script above works. Switching back to the builder version fails again.

**EDIT 2:**

The file `samples/index.html` also has a not working editor in the build version.
Same goes for the `samples/toolbarconfigurator/index.html` which doesn't work.

**Comment by f1ames** [comment]
I have tested both `standard` and `full` builds downloaded from https://ckeditor.com/cke4/builder with latest Chrome (73.0.3683.103 (Official Build) (64-bit)) and it works fine (both `samples/index.html` and script provided above). However, I'm on High Sierra (10.13.6 (17G65)) so it's not identical environment.

@xoniq Could you provide exact steps which led you to not working editor so we can be sure that we are testing the same scenario?

**Comment by xoniq** [comment]
@f1ames My stepts at this time to reproduce:

- Go to https://ckeditor.com/cke4/builder to build a custom version.
- Select `Icy Orange` as skin (also tried `Flat`).
- Leave everything as it is.
- Optimized version.
- Download. (Mine came as `ckeditor_4.11.3_ed3bec5393c3.zip`)
- Extract the zip.
- Add a `test.html` inside the extracted `ckeditor` folder.
- Add above HTML inside.
- Test `test.html` in browser. The editor loads, but doesn't do anything.

Tested right now on `Google Chrome Version 73.0.3683.103 (Official build) (64-bit)`.

For full disclosure I added uploaded it to WeTransfer to make sure you can test the exact same zip file as I got (`ckeditor_4.11.3_ed3bec5393c3.zip`):
https://we.tl/t-dD46ESy9WO

**Comment by xoniq** [comment]
It seems to be an plugin breaking stuff. But I cannot find which one this should be. When I run the builder incognito (without pre selected plugins) it actually does work. (Should have tries this first, blame on me).

Will try a few more times to see if I can find which plugin breaks the system.

**Comment by wwalc** [comment]
There are markdown and qrc 3rd party plugins included. Try investigating there. `config.removePlugins` should help in debugging.

**Comment by xoniq** [comment]
I tested again with only **adding** plugins, still working. Must be broken because I removed a few unused plugins. So it's not about the newly added plugins, but on deleting existing from within the builder.

**Comment by xoniq** [comment]
I think I found it. I downloaded perhaps 20 to 25 times with specific plugins deleted, it starts to fail when I remove `wysiwygarea` from CKEditor (my application doesn't support iframes).

**Comment by f1ames** [comment]
@xoniq thanks for detailed investigation 👍 

I can confirm that removing `wysiwygarea` causes some issue. However, from what I have tested removing it (`Iframe Editing Area`) breaks _Source_ version. The _Optimized_ one still works (fallbacks to inline editor). So the other way around than you have reported 🤔 

The `wysiwygarea` (`Iframe Editing Area`) is basically responsible for creating editable area so one can insert/modify the content. If you cannot use iframe one you can switch this plugin with `divarea` (`Div Editing Area`) which uses `<div>` element instead of `<iframe>`. One of this plugin is necessary to make editor work correctly.

One thing I'm not 100% sure is why optimized version works in such cases. Probably the builder adds `divarea` plugin if no editing area plugin is present.

**Comment by xoniq** [comment]
Weird indeed. Well at least we sorted it out. Either one of these need to be present, this issue can be closed and is clear what caused it.

I was thinking that plugin was used for supporting iframe elements within the editor, I forgot about the fact that the editor itself also uses an iframe, so it's logical this is needed for that to work. (when you're not using div)
